/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Classes.MailSender;
import Classes.PropertiesClass;
import Classes.SQLConnection;
import java.io.File;
import javax.swing.*;

/**
 *
 * @author Sowa
 */
public class DocumentsPanel extends javax.swing.JPanel {

     public static DocumentsPanel documentsPanel;
     SQLConnection sqlConnector;
     String[] fileNames;
     String selectedEvent;
     String selectedEventStatus;
     int selectedEventID;
     String userGroup;
     JPanel parentPanel;
     
    public DocumentsPanel(String event, String userGroup, JPanel parentPanel) {
        initComponents();
        Classes.FileManager fileManagerInstance = new Classes.FileManager();
        documentsPanel = this;
        this.parentPanel = parentPanel;
        this.userGroup = userGroup;
        selectedEvent = event;
        
        jTextField1.setText(selectedEvent);
        sqlConnector = SQLConnection.sqlConnector;
        deleteButton.setEnabled(false);
        downloadButton.setEnabled(false);
        addLabelButton.setVisible(false);
        addLabelButton.setEnabled(false);
        openButton.setEnabled(false);
        String query = "SELECT ID FROM "+PropertiesClass.props.DB_NAME+".Transports WHERE BLNumber='"+selectedEvent+"'";
        selectedEventID = Integer.parseInt(sqlConnector.getQueryFirstElement(query));
        query = "SELECT DataValue FROM "+PropertiesClass.props.DB_NAME+".Group WHERE DataName='"+userGroup+"'";
        int userValue = Integer.parseInt(sqlConnector.getQueryFirstElement(query));
        query = "SELECT s.DataName FROM "+PropertiesClass.props.DB_NAME+".Status s, "+PropertiesClass.props.DB_NAME+".Transports t WHERE t.Status_ID = s.ID AND t.BLNumber ='"+selectedEvent+"'";
        selectedEventStatus = sqlConnector.getQueryFirstElement(query);
        System.out.println("status: "+selectedEventStatus);
        setGUI(userValue);
        if(selectedEventStatus.contentEquals("AC") || selectedEventStatus.contentEquals("Archived"))
            {
                System.out.println("Jestem w ifie");
             deleteButton.setVisible(false);
             uploadButton.setVisible(false);
            } 
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        uploadButton = new javax.swing.JButton();
        downloadButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addLabelButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        openButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        uploadButton.setText("Upload Files");
        uploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadButtonActionPerformed(evt);
            }
        });

        downloadButton.setText("Download File");
        downloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete File");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Files:");
        jLabel1.setToolTipText("");

        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Event:");

        jTextField1.setEditable(false);

        jLabel3.setText("Labels:");

        addLabelButton.setText("Add Label");
        addLabelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLabelButtonActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel4.setText("File Description:");

        jTextField2.setEditable(false);

        jTextField5.setEditable(false);

        jTextField4.setEditable(false);

        jLabel6.setText("File Name:");

        jLabel7.setText("File Type:");

        jLabel8.setText("Updated Date:");

        jTextField6.setEditable(false);

        jLabel9.setText("Updated By:");

        jTextArea2.setColumns(20);
        jTextArea2.setEditable(false);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jLabel10.setText("File Active:");

        jTextField7.setEditable(false);

        openButton.setText("Open File");
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(161, 161, 161)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel10)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(uploadButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(downloadButton, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                            .addComponent(addLabelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                            .addComponent(openButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField7)
                                    .addComponent(jTextField6)
                                    .addComponent(jTextField5)
                                    .addComponent(jTextField4)
                                    .addComponent(jTextField2)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(166, 166, 166)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(openButton)
                        .addGap(18, 18, 18)
                        .addComponent(downloadButton)
                        .addGap(18, 18, 18)
                        .addComponent(uploadButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteButton)
                        .addGap(18, 18, 18)
                        .addComponent(addLabelButton)
                        .addGap(18, 18, 18)
                        .addComponent(backButton)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void refreshItemList(){
        
        DefaultListModel listModel = new DefaultListModel();
        String query ="SELECT FileName FROM "+PropertiesClass.props.DB_NAME+".LinkedDoc WHERE Transports_ID='"+selectedEventID+"';";
        fileNames = sqlConnector.getQueryFirstColumn(query);
        
        for(int i=0;i<fileNames.length;i++)
        {       
            listModel.addElement(fileNames[i]);
        }
        jList1.setModel(listModel);
        jTextField2.setText("");
        jTextArea2.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextArea1.setText("");
    }
    private void setGUI(int userValue){

        switch(userValue){ 
            case 0 :{   //Admin=0     
            }break;
            case 1 :{  //Buyer=1
            //deleteButton.setVisible(false);
            //addLabelButton.setVisible(false);
            //uploadButton.setVisible(false);
            }break;
            case 2:{ //Vendor=2
            deleteButton.setVisible(false);
            //addLabelButton.setVisible(false);
            //uploadButton.setVisible(false);    
            }break;
            case 3:{  //PU=3
                               
            }break;
            case 4:{  //Impex=4
                
            }break;
            case 5:{  //Customs Agency=5
            deleteButton.setVisible(false);
            //addLabelButton.setVisible(false);
            uploadButton.setVisible(false);    
            }break;
            case 6:{  //Transport=6
            deleteButton.setVisible(false);
            addLabelButton.setVisible(false);
            uploadButton.setVisible(false);    
            }break;
            case 7:{  //Courier=7
            //deleteButton.setVisible(false);
            addLabelButton.setVisible(false);
            //uploadButton.setVisible(false); 
            }break;
            default:{
            deleteButton.setVisible(false);
            addLabelButton.setVisible(false);
            uploadButton.setVisible(false);     
            }
        }
    }
    private void uploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadButtonActionPerformed
         UploadPanel upPanel = new UploadPanel(selectedEventID,selectedEvent);
         Classes.CDSApplet.cdsApplet.add(upPanel);
         DocumentsPanel.documentsPanel.setVisible(false);
    }//GEN-LAST:event_uploadButtonActionPerformed
            
    private void downloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        int index = jList1.getSelectedIndex();
        String fileName =fileNames[index];
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = chooser.showSaveDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            Classes.FileManager fileManagerInstance = new Classes.FileManager();
            fileManagerInstance.fileRead(file,fileName);
            sqlConnector.addLogToTable("File Downloaded", MainPanel.userLogin, fileName, selectedEventID);
            JOptionPane.showMessageDialog(this, "File downloaded.");
            this.repaint();         
        }
    }//GEN-LAST:event_downloadButtonActionPerformed
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        documentsPanel.setVisible(false);
        parentPanel.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed
    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
         if (evt.getValueIsAdjusting() == false) {
         int selectedIndex = jList1.getSelectedIndex();
        if (selectedIndex == -1) {
        //No selection, disable fire button.
            deleteButton.setEnabled(false);
            downloadButton.setEnabled(false);
            addLabelButton.setEnabled(false);
            openButton.setEnabled(false);
                    } else {
        //Selection, enable the fire button.
            
            deleteButton.setEnabled(true);    
            downloadButton.setEnabled(true);
            addLabelButton.setEnabled(true);  
            openButton.setEnabled(true);
            loadItemDetails(selectedIndex);
        }
    }
    }//GEN-LAST:event_jList1ValueChanged
    private void addLabelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLabelButtonActionPerformed
        AddLabelPanel alPanel= new AddLabelPanel(jList1.getSelectedValue().toString());
        Classes.CDSApplet.cdsApplet.add(alPanel);
        DocumentsPanel.documentsPanel.setVisible(false);

    }//GEN-LAST:event_addLabelButtonActionPerformed
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int index = jList1.getSelectedIndex();
        String fileName =fileNames[index];
        String query = "SELECT ID FROM "+PropertiesClass.props.DB_NAME+".Transports WHERE BLNumber='"+selectedEvent+"'";
        int transportID = Integer.parseInt(sqlConnector.getQueryFirstElement(query));   
        sqlConnector.deleteFileFromBase(fileName,transportID); // delete file from database
        sqlConnector.addLogToTable("File Deleted", MainPanel.userLogin, fileName, selectedEventID);
        JOptionPane.showMessageDialog(this, "File deleted.");
        refreshItemList();         
    }//GEN-LAST:event_deleteButtonActionPerformed
   
    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
        try {
            int index = jList1.getSelectedIndex();
            String fileName =fileNames[index];
            int dotIndex = fileName.lastIndexOf(".");
            String fileType = fileName.substring(dotIndex);
            //File tempFile = new File("tempFile.xlsx");
            File tempFile = File.createTempFile("tempFile", fileType);
            // Delete temp file when program exits.
            tempFile.deleteOnExit();
            sqlConnector.openFileFromBase(fileName,tempFile);
        }
        catch(Exception ex) {
        System.out.println("Blad w openFile");
        System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_openButtonActionPerformed
    private void loadItemDetails(int selectedIndex){
     String query = "SELECT a.ID, a.FileName, a.FileDescription, a.FileType, a.UpdatedBy, a.UpdatedBy, a.FileActive, a.Transports_ID FROM "+PropertiesClass.props.DB_NAME+".LinkedDoc a WHERE FileName = '"+fileNames[selectedIndex]+"';";
        String[] documentDetails = sqlConnector.getQueryFirstRow(query,8);
        jTextField2.setText(documentDetails[1]);
        jTextArea2.setText(documentDetails[2]);
        jTextField4.setText(documentDetails[3]);
        jTextField5.setText(documentDetails[4]);
        jTextField6.setText(documentDetails[5]);
        jTextField7.setText(documentDetails[6]);
        query = "SELECT ID FROM "+PropertiesClass.props.DB_NAME+".LinkedDoc WHERE FileName='"+jList1.getSelectedValue()+"' AND Transports_ID = '"+selectedEventID+"';";
        int docID = Integer.parseInt(sqlConnector.getQueryFirstElement(query));   
        query = "SELECT Label FROM "+PropertiesClass.props.DB_NAME+".Label WHERE LinkedDoc_ID = '"+docID+"';";
        jTextArea1.setText("");
        if(sqlConnector.checkQueryAppearence(query))
        {
          String[] labels = sqlConnector.getQueryFirstColumn(query);
        int i=0;
        while(i<labels.length){
            
            jTextArea1.setText(jTextArea1.getText()+labels[i]+"\n");
            i++;
        }  
        }
        
        
           
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addLabelButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton downloadButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JButton openButton;
    private javax.swing.JButton uploadButton;
    // End of variables declaration//GEN-END:variables
}
