/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Classes.PropertiesClass;
import Classes.SQLConnection;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Sowa
 */
public class EditVendorPanel extends javax.swing.JPanel {

    public static EditVendorPanel editVendorPanel;
    String selectedVendor;
    SQLConnection sqlConnector;
    String[] vendorNames;
    /**
     * Creates new form NewVendorPanel
     */
    public EditVendorPanel(String vendor) {
        initComponents();
        editVendorPanel = this;
        selectedVendor = vendor;
        sqlConnector = SQLConnection.sqlConnector;
        refreshItemList();
        loadVendorDetails();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        editButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jCheckBox2 = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));

        jLabel3.setText("Vendor Description:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel2.setText("Vendor Value:");

        jLabel1.setText("Vendor Name:");

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Vendor Active");

        editButton.setText("Edit Vendor");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("BACK");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Vendor e-mail:");

        jCheckBox2.setText("Master Unit");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(27, 27, 27)
                        .addComponent(jTextField3))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3)
                    .addComponent(jCheckBox1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox2)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(259, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        editVendorPanel.setVisible(false);
        VendorPanel.vendorPanel.setVisible(true);
    }//GEN-LAST:event_cancelButtonActionPerformed
private void refreshItemList() {

        
        DefaultComboBoxModel vendorModel = new DefaultComboBoxModel();
        String query = "SELECT DataName FROM "+PropertiesClass.props.DB_NAME+".Vendor WHERE DataActive ='1' AND MasterUnit ='1' ORDER BY DataName ASC ;";
        vendorNames = sqlConnector.getQueryFirstColumn(query);       
        for (String vendorName : vendorNames) {
            vendorModel.addElement(vendorName);
        }
        jComboBox1.setModel(vendorModel);              
        jComboBox1.setSelectedIndex(0);

    }
    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed

        String query = "SELECT * FROM "+PropertiesClass.props.DB_NAME+".Vendor WHERE DataName='"+jTextField1.getText()+"';";
        boolean check = sqlConnector.checkQueryAppearence(query);
        if((!check || jTextField1.getText().contentEquals(selectedVendor)) && !(jTextField1.getText().isEmpty()) && !(jTextField3.getText().isEmpty())){
            if (jCheckBox2.isSelected()) 
        {
            query = "SELECT ID FROM "+PropertiesClass.props.DB_NAME+".Vendor WHERE DataName='"+selectedVendor+"';";
            int vendorID = Integer.parseInt(sqlConnector.getQueryFirstElement(query));
            sqlConnector.updateTable("Vendor", jTextField1.getText(),jTextField1.getText(), jTextField2.getText(), jTextArea1.getText(), jCheckBox1.isSelected(), jTextField3.getText(), jCheckBox2.isSelected(), vendorID);
        }
        else  
        {
            query = "SELECT MasterUnitId FROM "+PropertiesClass.props.DB_NAME+".Vendor WHERE DataName='"+jComboBox1.getSelectedItem().toString()+"';";
            int vendorID = Integer.parseInt(sqlConnector.getQueryFirstElement(query));
            sqlConnector.updateTable("Vendor", jTextField1.getText(),jTextField1.getText(), jTextField2.getText(), jTextArea1.getText(), jCheckBox1.isSelected(), jTextField3.getText(), jCheckBox2.isSelected(), vendorID);
        }
        editVendorPanel.setVisible(false);
        VendorPanel.vendorPanel.setVisible(true);
        VendorPanel.vendorPanel.refreshItemList();
       }else JOptionPane.showMessageDialog(editVendorPanel, "Vendor name or email is empty or already exists! Chose new name or leave previous one.");
        
    }//GEN-LAST:event_editButtonActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        jComboBox1.setEnabled(!jCheckBox2.isSelected());
    }//GEN-LAST:event_jCheckBox2ActionPerformed
    private void loadVendorDetails(){
       String query = "SELECT * FROM "+PropertiesClass.props.DB_NAME+".Vendor WHERE DataName = '"+selectedVendor+"';";
        String[] vendorDetails = sqlConnector.getQueryFirstRow(query,10);
        query = "SELECT DataName FROM "+PropertiesClass.props.DB_NAME+".Vendor WHERE ID = '"+vendorDetails[9]+"';";
        String masterUnitName = sqlConnector.getQueryFirstElement(query);
        jTextField1.setText(vendorDetails[1]);
        jTextField2.setText(vendorDetails[2]);
        jTextField3.setText(vendorDetails[7]);
        jTextArea1.setText(vendorDetails[3]);
        if(vendorDetails[4].contentEquals("1")){
         jCheckBox1.setSelected(true);   
        }else jCheckBox1.setSelected(false);
        if(vendorDetails[8].contentEquals("1")){
         jCheckBox2.setSelected(true);
         jComboBox1.setEnabled(false);
        }else 
        {
            jCheckBox2.setSelected(false);
            jComboBox1.setEnabled(true);
            jComboBox1.setSelectedItem(masterUnitName);
        }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton editButton;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
