/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Classes.PropertiesClass;
import Classes.SQLConnection;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Sowa
 */
public class EditUserPanel extends javax.swing.JPanel {

    //ver.1.02 New field added to describe Courier user group -- 29.11.2014
    
    public static EditUserPanel editUserPanel;
    SQLConnection sqlConnector;
    String[] groupNames;
    String[] carrierNames;
    String selectedUser;
    /**
     * Creates new form NewVendorPanel
     */
    public EditUserPanel(String user) {
        initComponents();
        editUserPanel = this;
        sqlConnector = SQLConnection.sqlConnector;
        selectedUser = user;
        editButton.setEnabled(false);
        jComboBox2.setVisible(false);
        jComboBox2.setSelectedIndex(-1);
        carrierLabel.setVisible(false);
        refreshItemList();
        loadItemDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        carrierLabel = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();

        setMinimumSize(new java.awt.Dimension(800, 600));

        jLabel3.setText("User Description:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel2.setText("Last Name:");

        jLabel1.setText("Login:");

        editButton.setText("Edit User");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("BACK");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Password:");

        jLabel5.setText("First Name:");

        jLabel6.setText("Company Code:");

        jLabel7.setText("e-mail:");

        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel8.setText("User Groups:");

        carrierLabel.setText("Carrier Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(339, 339, 339))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                                    .addComponent(jTextField3)
                                    .addComponent(jPasswordField1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(carrierLabel)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField6)
                                    .addComponent(jTextField5)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carrierLabel))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshItemList() {

        DefaultListModel listModel = new DefaultListModel();
        String query = "SELECT DataName FROM "+PropertiesClass.props.DB_NAME+".Group WHERE DataActive ='1' ORDER BY DataName ASC;";
        groupNames = sqlConnector.getQueryFirstColumn(query);

        for (int i = 0; i < groupNames.length; i++) {
            listModel.addElement(groupNames[i]);
        }
        jList1.setModel(listModel);
        
        DefaultComboBoxModel comboModel = new DefaultComboBoxModel();
        query = "SELECT DataName FROM "+PropertiesClass.props.DB_NAME+".Carrier WHERE DataActive ='1' ORDER BY DataName ASC;";
        carrierNames = sqlConnector.getQueryFirstColumn(query);

        for (int i = 0; i < carrierNames.length; i++) {
            comboModel.addElement(carrierNames[i]);
        }
        jComboBox2.setModel(comboModel);        
    }
    private void loadItemDetails(){
     String query = "SELECT * FROM "+PropertiesClass.props.DB_NAME+".User WHERE Login = '"+selectedUser+"';";
        String[] userDetails = sqlConnector.getQueryFirstRow(query,12);
        jTextField1.setText(userDetails[1]);
        jPasswordField1.setText(userDetails[2]);
        jTextField3.setText(userDetails[3]);
        jTextField4.setText(userDetails[4]);
        jTextField6.setText(userDetails[5]);
        jTextField5.setText(userDetails[6]);
        jTextArea1.setText(userDetails[7]);

        query = "SELECT DataName FROM "+PropertiesClass.props.DB_NAME+".Group WHERE ID = '"+userDetails[10]+"';";
        String groupName = sqlConnector.getQueryFirstElement(query);
        jList1.setSelectedValue(groupName, true);
        
        query = "SELECT DataName FROM "+PropertiesClass.props.DB_NAME+".Carrier WHERE ID = '"+userDetails[11]+"';";       
        if(sqlConnector.checkQueryAppearence(query)) jComboBox2.setSelectedItem(sqlConnector.getQueryFirstElement(query));
        else jComboBox2.setSelectedIndex(-1);
        
        
        
                   
    }
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        editUserPanel.setVisible(false);
        UserPanel.userPanel.setVisible(true);
    }//GEN-LAST:event_cancelButtonActionPerformed
    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        String query = "SELECT * FROM "+PropertiesClass.props.DB_NAME+".User WHERE Login='"+jTextField1.getText()+"';";
        boolean check = sqlConnector.checkQueryAppearence(query);
        if((!check || jTextField1.getText().contentEquals(selectedUser)) && !(jTextField1.getText().isEmpty())){
        query = "SELECT ID FROM "+PropertiesClass.props.DB_NAME+".Group WHERE DataName='"+jList1.getSelectedValue().toString()+"';";
        int groupID = Integer.parseInt(sqlConnector.getQueryFirstElement(query));
        
        int carrierID=-1;   
        if(jComboBox2.getSelectedIndex()!=-1){
           query = "SELECT ID FROM "+PropertiesClass.props.DB_NAME+".Carrier WHERE DataName='"+jComboBox2.getSelectedItem().toString()+"';";
            if(sqlConnector.checkQueryAppearence(query)) carrierID = Integer.parseInt(sqlConnector.getQueryFirstElement(query));         
        }
        
        sqlConnector.updateUser(jTextField1.getText(), new String(jPasswordField1.getPassword()), jTextField3.getText(), jTextField4.getText(), jTextField6.getText(), jTextField5.getText(), jTextArea1.getText(), MainPanel.userLogin, groupID,carrierID,selectedUser);
        editUserPanel.setVisible(false);
        UserPanel.userPanel.setVisible(true);
        UserPanel.userPanel.refreshItemList();
       }else JOptionPane.showMessageDialog(editUserPanel, "User login is empty or already exists! Chose new login or leave previous one.");
        
    }//GEN-LAST:event_editButtonActionPerformed
    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        if (evt.getValueIsAdjusting() == false) {
            int selectedIndex = jList1.getSelectedIndex();
            if (selectedIndex == -1) {
                //No selection, disable fire button.
                editButton.setEnabled(false);
            } else {
                if(jList1.getSelectedValue().toString().matches("Courier") ) {
                    jComboBox2.setVisible(true);
                    jComboBox2.setSelectedIndex(0);
                    carrierLabel.setVisible(true);
                }else 
                {
                    jComboBox2.setSelectedIndex(-1);
                    jComboBox2.setVisible(false);
                    carrierLabel.setVisible(false);
                }
                //Selection, enable the fire button.
                editButton.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jList1ValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel carrierLabel;
    private javax.swing.JButton editButton;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList jList1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
