/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;


import Classes.MailSender;
import Classes.PropertiesClass;
import Classes.SQLConnection;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;


/**
 *
 * @author Sowa
 */
public class LoginPanel extends javax.swing.JPanel {

    public static LoginPanel loginPanel;
    public LoginPanel() {
        initComponents();
        jLabel4.setVisible(false);
        loginPanel = this;
        try{
         BufferedImage myPicture = ImageIO.read(getClass().getClassLoader().getResource("Images/logo.png"));
         logoLabel.setIcon(new ImageIcon(myPicture));
        }catch(Exception e){System.out.println("Nie znaleziono pliku z logo!");
        System.out.println(getClass().getClassLoader().getResource("/Images/logo.png"));}
        try{
         BufferedImage myPicture = ImageIO.read(getClass().getClassLoader().getResource("Images/name.png"));
         nameLabel.setIcon(new ImageIcon(myPicture));
        }catch(Exception e){System.out.println("Nie znaleziono pliku z nazwa!");
        System.out.println(getClass().getClassLoader().getResource("/Images/name.png"));}
        //JRootPane rootPane = CDSApplet.cdsApplet.getRootPane();
        //rootPane.setDefaultButton(jButton1);
        //jButton1.getInputMap().put(KeyStroke.getKeyStroke("Enter"),"doSomething");
        //jButton1.getActionMap().put("doSomething", anAction);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("SIGN IN");

        jLabel2.setText("Login:");

        jLabel3.setText("Password:");

        jButton1.setText("Sign in");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Wrong login or password! Try again.");

        logoLabel.setToolTipText("");

        nameLabel.setMaximumSize(new java.awt.Dimension(200, 100));
        nameLabel.setMinimumSize(new java.awt.Dimension(200, 100));
        nameLabel.setPreferredSize(new java.awt.Dimension(200, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1)
                                    .addComponent(jPasswordField1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel1))
                            .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(304, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(165, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String providedLogin, providedPassword;
        providedPassword = new String(jPasswordField1.getPassword());
        providedLogin = jTextField1.getText();
        Classes.SQLConnection sqlConnector = new Classes.SQLConnection();
        String query = "SELECT * FROM "+PropertiesClass.props.DB_NAME+".User WHERE Login='"+providedLogin+"' AND Password = '"+providedPassword+"' ;";
        boolean check = sqlConnector.checkQueryAppearence(query);
        query = "SELECT DataName FROM "+PropertiesClass.props.DB_NAME+".Group,"+PropertiesClass.props.DB_NAME+".User WHERE "+PropertiesClass.props.DB_NAME+".User.Login = '"+providedLogin+"' AND "+PropertiesClass.props.DB_NAME+".User.Password = '"+providedPassword+"' AND "+PropertiesClass.props.DB_NAME+".Group.ID="+PropertiesClass.props.DB_NAME+".User.Group_ID;";
        String userGroup = sqlConnector.getQueryFirstElement(query);
        //System.out.println("password accepted: "+check);
        if(!check) jLabel4.setVisible(true);
        else 
        {
         jLabel4.setVisible(false);
         MainPanel mPanel = new MainPanel(userGroup,providedLogin);
         Classes.CDSApplet.cdsApplet.add(mPanel);
         LoginPanel.loginPanel.setVisible(false);
         mPanel.refreshItemList();
//         MailSender mail= new MailSender();
//         try{
//            String[] address = { "przemektarkowski@wp.pl", "sowaznebrowa@gmail.com", null };
//            mail.send(address,"Witaj","Zalogowałeś się");
 //        }catch(Exception e){System.out.println("Błąd w mailu: "+e);}
         
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public void refresh(){
        jPasswordField1.setText("");
        jTextField1.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
}
