/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Classes.PropertiesClass;
import Classes.SQLConnection;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

/**
 *
 * @author Przemysław Tarkowski
 */
public class MainPanel extends javax.swing.JPanel {

    public static MainPanel mainPanel;
    String userGroup;
    String[] eventNames;
    public static String userLogin;
    SQLConnection sqlConnector;
    int userValue;
    String userMail,userCarrier;
    
    public MainPanel() {
        initComponents();
        mainPanel = this;
        eventDocumentsButton.setEnabled(false);
        eventCommentsButton.setEnabled(false);
        eventStatusButton.setEnabled(false);
        logsButton.setEnabled(false);
    }
    public MainPanel(String userGroup, String login) {
        initComponents();
        mainPanel = this;
        this.userGroup = userGroup;
        userLogin = login;
        jLabel3.setText(login);
        eventDocumentsButton.setEnabled(false);
        eventCommentsButton.setEnabled(false);
        eventStatusButton.setEnabled(false);
        logsButton.setEnabled(false);
        sqlConnector = SQLConnection.sqlConnector;
        String query = "SELECT DataValue FROM "+PropertiesClass.props.DB_NAME+".Group WHERE DataName='"+userGroup+"';";
        userValue = Integer.parseInt(sqlConnector.getQueryFirstElement(query));
        
        userCarrier = null;        
        if (userGroup.matches("Courier"))
        {       
        query = "SELECT c.DataName FROM "+PropertiesClass.props.DB_NAME+".Carrier c, "+PropertiesClass.props.DB_NAME+".User u WHERE u.Carrier_ID = c.ID AND u.Login = '"+userLogin+"';";
        if(sqlConnector.checkQueryAppearence(query)) userCarrier = sqlConnector.getQueryFirstElement(query);     
        }
        
        query = "SELECT `E-mail` FROM "+PropertiesClass.props.DB_NAME+".User WHERE Login='"+login+"';";
        userMail = sqlConnector.getQueryFirstElement(query);
        setGUI(userValue);
        try{
         BufferedImage myPicture = ImageIO.read(getClass().getClassLoader().getResource("Images/logo.png"));
         logoLabel2.setIcon(new ImageIcon(myPicture));
        }catch(Exception e){System.out.println("Nie znaleziono pliku z logo!");
        System.out.println(getClass().getClassLoader().getResource("/Images/logo.png"));}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newEventButton = new javax.swing.JButton();
        eventDocumentsButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        eventStatusButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        vendorButton = new javax.swing.JButton();
        carrierButton = new javax.swing.JButton();
        statusesButton = new javax.swing.JButton();
        groupsButton = new javax.swing.JButton();
        usersButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        logsButton = new javax.swing.JButton();
        filterTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        labelImage = new javax.swing.JLabel();
        changePassButton = new javax.swing.JButton();
        RefreshButton = new javax.swing.JButton();
        logoLabel = new javax.swing.JLabel();
        logoLabel2 = new javax.swing.JLabel();
        eventCommentsButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setMaximumSize(new java.awt.Dimension(1024, 800));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        newEventButton.setText("Create New Transport Event");
        newEventButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEventButtonActionPerformed(evt);
            }
        });

        eventDocumentsButton.setText("Show Event Documents");
        eventDocumentsButton.setName(""); // NOI18N
        eventDocumentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventDocumentsButtonActionPerformed(evt);
            }
        });

        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setText("Events:");

        eventStatusButton.setText("Change Event Status");
        eventStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventStatusButtonActionPerformed(evt);
            }
        });

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("User:");

        vendorButton.setText("Vendors");
        vendorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendorButtonActionPerformed(evt);
            }
        });

        carrierButton.setText("Carriers");
        carrierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carrierButtonActionPerformed(evt);
            }
        });

        statusesButton.setText("Statuses");
        statusesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusesButtonActionPerformed(evt);
            }
        });

        groupsButton.setText("Groups");
        groupsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupsButtonActionPerformed(evt);
            }
        });

        usersButton.setText("Users");
        usersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("PONumber:");

        jLabel5.setText("Event Number (BL or AWB):");

        jTextField2.setEditable(false);

        jTextField1.setEditable(false);

        jTextField5.setEditable(false);

        jTextField4.setEditable(false);

        jLabel6.setText("Update By:");

        jLabel7.setText("Update Date:");

        jLabel8.setText("Status Name:");

        jTextField3.setEditable(false);

        jTextField6.setEditable(false);

        jTextField7.setEditable(false);

        jLabel9.setText("Carrier Name:");

        jLabel10.setText("Vendor Name:");

        jLabel11.setText("Buyer Name:");

        jTextField8.setEditable(false);

        logsButton.setText("Logs");
        logsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logsButtonActionPerformed(evt);
            }
        });

        filterTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterTextFieldKeyReleased(evt);
            }
        });

        jLabel12.setText("Event Filter:");

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jLabel13.setText("Number of annexes:");

        jTextField9.setEditable(false);

        labelImage.setMaximumSize(new java.awt.Dimension(70, 70));
        labelImage.setMinimumSize(new java.awt.Dimension(70, 70));
        labelImage.setName(""); // NOI18N
        labelImage.setPreferredSize(new java.awt.Dimension(70, 70));

        changePassButton.setText("Change Password");
        changePassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePassButtonActionPerformed(evt);
            }
        });

        RefreshButton.setText("Refresh");
        RefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshButtonActionPerformed(evt);
            }
        });

        eventCommentsButton.setText("Show Event Comments");
        eventCommentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventCommentsButtonActionPerformed(evt);
            }
        });

        jLabel14.setText("Comments:");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logoLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eventDocumentsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newEventButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eventStatusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vendorButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(carrierButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(statusesButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(groupsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usersButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(changePassButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eventCommentsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTextField7)
                                    .addComponent(jTextField8)
                                    .addComponent(jTextField2)
                                    .addComponent(jTextField4)
                                    .addComponent(jTextField5)
                                    .addComponent(jTextField3)
                                    .addComponent(jTextField1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RefreshButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filterTextField))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logoLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newEventButton)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eventDocumentsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eventCommentsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eventStatusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(filterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(2, 2, 2)
                        .addComponent(RefreshButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vendorButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(carrierButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusesButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(groupsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(usersButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(logsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(changePassButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))))
                        .addGap(204, 204, 204)
                        .addComponent(logoLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(labelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void setGUI(int userValue){
        
        switch(userValue){
            case 0:{ //Admin=0
             
            }break;
            case 1:{ //Buyer=1
            //newEventButton.setVisible(false);
            vendorButton.setVisible(false);
            carrierButton.setVisible(false);
            statusesButton.setVisible(false);
            groupsButton.setVisible(false);
            usersButton.setVisible(false);
            //eventStatusButton.setVisible(false);
            }break;
            case 2:{ //Vendor=2
            //newEventButton.setVisible(false);
            vendorButton.setVisible(false);
            carrierButton.setVisible(false);
            statusesButton.setVisible(false);
            groupsButton.setVisible(false);
            usersButton.setVisible(false);
            eventStatusButton.setVisible(false);
            }break;
            case 3:{ //PU=3
            newEventButton.setVisible(false);
            vendorButton.setVisible(false);
            carrierButton.setVisible(false);
            statusesButton.setVisible(false);
            groupsButton.setVisible(false);
            usersButton.setVisible(false);
            eventStatusButton.setVisible(false);
            }break;
            case 4:{ //Impex=4
            newEventButton.setVisible(false);
            vendorButton.setVisible(false);
            carrierButton.setVisible(false);
            statusesButton.setVisible(false);
            groupsButton.setVisible(false);
            usersButton.setVisible(false);
            //eventStatusButton.setVisible(false);
            }break;
            case 5:{ //Customs Agency=5
            newEventButton.setVisible(false);
            vendorButton.setVisible(false);
            carrierButton.setVisible(false);
            statusesButton.setVisible(false);
            groupsButton.setVisible(false);
            usersButton.setVisible(false);
            //eventStatusButton.setVisible(false);
            }break;
            case 6:{ //Transport=6
            vendorButton.setVisible(false);
            carrierButton.setVisible(false);
            statusesButton.setVisible(false);
            groupsButton.setVisible(false);
            usersButton.setVisible(false);
            eventStatusButton.setVisible(false);
            }break;
            case 7:{ //Courier=7
            vendorButton.setVisible(false);
            carrierButton.setVisible(false);
            statusesButton.setVisible(false);
            groupsButton.setVisible(false);
            usersButton.setVisible(false);
            //eventStatusButton.setVisible(false);
            }break;
            default:{
            newEventButton.setVisible(false);
            vendorButton.setVisible(false);
            carrierButton.setVisible(false);
            statusesButton.setVisible(false);
            groupsButton.setVisible(false);
            usersButton.setVisible(false);
            eventStatusButton.setVisible(false);
            }break;
        }
    }
    
    private void eventDocumentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventDocumentsButtonActionPerformed
         String selectedEvent = jList1.getSelectedValue().toString();
         DocumentsPanel dPanel = new DocumentsPanel(selectedEvent, userGroup, mainPanel);
         Classes.CDSApplet.cdsApplet.add(dPanel);
         MainPanel.mainPanel.setVisible(false);
         dPanel.refreshItemList();
    }//GEN-LAST:event_eventDocumentsButtonActionPerformed
    private void newEventButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEventButtonActionPerformed
         NewEventPanel ePanel = new NewEventPanel(userCarrier);
         Classes.CDSApplet.cdsApplet.add(ePanel);
         MainPanel.mainPanel.setVisible(false);
    }//GEN-LAST:event_newEventButtonActionPerformed
    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed

        mainPanel.setVisible(false);
        SQLConnection.sqlConnector.closeConnection();
        LoginPanel.loginPanel.setVisible(true);
        LoginPanel.loginPanel.refresh();
       
    }//GEN-LAST:event_logoutButtonActionPerformed
    private void eventStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventStatusButtonActionPerformed
         String selectedEvent = jList1.getSelectedValue().toString();
         EventStatusPanel evsPanel = new EventStatusPanel(selectedEvent,mainPanel,userGroup,userCarrier);
         Classes.CDSApplet.cdsApplet.add(evsPanel);
         MainPanel.mainPanel.setVisible(false);
    }//GEN-LAST:event_eventStatusButtonActionPerformed
    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
       if (evt.getValueIsAdjusting() == false) {
        int selectedIndex = jList1.getSelectedIndex();
        if (selectedIndex == -1) {
        //No selection, disable fire button.
            eventDocumentsButton.setEnabled(false);
            eventCommentsButton.setEnabled(false);
            eventStatusButton.setEnabled(false);
            logsButton.setEnabled(false);

        } else {
        //Selection, enable the fire button.
            eventDocumentsButton.setEnabled(true);
            eventCommentsButton.setEnabled(true);
            eventStatusButton.setEnabled(true);
            logsButton.setEnabled(true);
             loadItemDetails(selectedIndex);
        }
       }
    }//GEN-LAST:event_jList1ValueChanged
    private void vendorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendorButtonActionPerformed
        VendorPanel vPanel= new VendorPanel();
        Classes.CDSApplet.cdsApplet.add(vPanel);
         MainPanel.mainPanel.setVisible(false);
         vPanel.refreshItemList();
    }//GEN-LAST:event_vendorButtonActionPerformed
    private void groupsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupsButtonActionPerformed
        GroupPanel gPanel= new GroupPanel();
        Classes.CDSApplet.cdsApplet.add(gPanel);
         MainPanel.mainPanel.setVisible(false);
         gPanel.refreshItemList();
    }//GEN-LAST:event_groupsButtonActionPerformed
    private void carrierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carrierButtonActionPerformed
        CarrierPanel cPanel= new CarrierPanel();
        Classes.CDSApplet.cdsApplet.add(cPanel);
         MainPanel.mainPanel.setVisible(false);
         cPanel.refreshItemList();
    }//GEN-LAST:event_carrierButtonActionPerformed
    private void statusesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusesButtonActionPerformed
        StatusPanel sPanel= new StatusPanel();
        Classes.CDSApplet.cdsApplet.add(sPanel);
         MainPanel.mainPanel.setVisible(false);
         sPanel.refreshItemList();
    }//GEN-LAST:event_statusesButtonActionPerformed
    private void usersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersButtonActionPerformed
        UserPanel uPanel= new UserPanel();
        Classes.CDSApplet.cdsApplet.add(uPanel);
         MainPanel.mainPanel.setVisible(false);
         uPanel.refreshItemList();
    }//GEN-LAST:event_usersButtonActionPerformed

    private void logsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logsButtonActionPerformed
        LogsPanel logPanel= new LogsPanel(jList1.getSelectedValue().toString(),mainPanel);
        Classes.CDSApplet.cdsApplet.add(logPanel);
         MainPanel.mainPanel.setVisible(false);
         logPanel.refreshItemList();
    }//GEN-LAST:event_logsButtonActionPerformed

    private void filterTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterTextFieldKeyReleased
         if(!filterTextField.getText().isEmpty()) refreshItemList(filterTextField.getText());
         else refreshItemList();
    }//GEN-LAST:event_filterTextFieldKeyReleased

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        SearchPanel sePanel = new SearchPanel(userGroup,userLogin,userMail,userCarrier);
         Classes.CDSApplet.cdsApplet.add(sePanel);
         MainPanel.mainPanel.setVisible(false);
         sePanel.refreshItemList();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void changePassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePassButtonActionPerformed
        ChangePassPanel cpPanel= new ChangePassPanel(userLogin);
        Classes.CDSApplet.cdsApplet.add(cpPanel);
         MainPanel.mainPanel.setVisible(false);
    }//GEN-LAST:event_changePassButtonActionPerformed

    private void RefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButtonActionPerformed
       if(!filterTextField.getText().isEmpty()) refreshItemList(filterTextField.getText());
       else refreshItemList();
    }//GEN-LAST:event_RefreshButtonActionPerformed

    private void eventCommentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventCommentsButtonActionPerformed
         String selectedEvent = jList1.getSelectedValue().toString();
         CommentsPanel cPanel = new CommentsPanel(selectedEvent, userGroup, mainPanel);
         Classes.CDSApplet.cdsApplet.add(cPanel);
         MainPanel.mainPanel.setVisible(false);
         cPanel.refreshCommentsList();
    }//GEN-LAST:event_eventCommentsButtonActionPerformed
    public void refreshItemList() {

        String query;
        switch(userValue){
            case 0:{ //Admin=0
             query = "SELECT BLNumber FROM "+PropertiesClass.props.DB_NAME+".Transports;";
            }break;
            case 1:{ //Buyer=1
             query = "SELECT BLNumber FROM "+PropertiesClass.props.DB_NAME+".Transports;";
            }break;
            case 2:{ //Vendor=2
             query = "SELECT BLNumber FROM "+PropertiesClass.props.DB_NAME+".Transports a, "+PropertiesClass.props.DB_NAME+".Status b WHERE a.Status_ID=b.ID AND a.UpdatedBy='"+userMail+"' AND (b.DataName='Opened' OR b.DataName='Completed' OR b.DataName='Correct' OR b.DataName='AC' OR b.DataName='Reopened');";
            }break;
            case 3:{ //PU=3
             query = "SELECT BLNumber FROM "+PropertiesClass.props.DB_NAME+".Transports a, "+PropertiesClass.props.DB_NAME+".Status b WHERE a.Status_ID=b.ID AND (b.DataName='Opened' OR b.DataName='AC' OR b.DataName='Reopened');";
            }break;
            case 4:{ //Impex=4
             query = "SELECT BLNumber FROM "+PropertiesClass.props.DB_NAME+".Transports a, "+PropertiesClass.props.DB_NAME+".Status b WHERE a.Status_ID=b.ID AND (b.DataName='Opened' OR b.DataName='Completed' OR b.DataName='Rejected' OR b.DataName='Correct' OR b.DataName='Archived' OR b.DataName='AC' OR b.DataName='Reopened');";
            }break;
            case 5:{ //Customs Agency=5
             //ver.1.01 Customs Agency must see all types of events -- 28.08.2014  
             //query = "SELECT BLNumber FROM "+PropertiesClass.props.DB_NAME+".Transports a, "+PropertiesClass.props.DB_NAME+".Status b WHERE a.Status_ID=b.ID AND (b.DataName='Completed' OR b.DataName='Correct' OR b.DataName='AC'OR b.DataName='Reopened');";
             query = "SELECT BLNumber FROM "+PropertiesClass.props.DB_NAME+".Transports a, "+PropertiesClass.props.DB_NAME+".Status b WHERE a.Status_ID=b.ID AND (b.DataName!='Opened');"; //AC don't want to see 'opened' status ver.1.01  -- 01.11.2014
            }break;
            case 6:{ //Transport=6
             query = "SELECT BLNumber FROM "+PropertiesClass.props.DB_NAME+".Transports;"; 
            }break;
            //ver.1.02 Added new user group (Courier) -- 30.11.2014    
            case 7:{ //Courier=7
             query = "SELECT BLNumber FROM "+PropertiesClass.props.DB_NAME+".Transports a, "+PropertiesClass.props.DB_NAME+".Carrier b WHERE a.Carrier_ID = b.ID AND b.DataName ='"+userCarrier+"' ;"; 
            }break;
            default:{
             query = "SELECT BLNumber FROM "+PropertiesClass.props.DB_NAME+".Transports;";    
            }break;
        }
        DefaultListModel listModel = new DefaultListModel();       
        eventNames = sqlConnector.getQueryFirstColumn(query);

        for (int i = 0; i < eventNames.length; i++) {
            listModel.addElement(eventNames[i]);
        }
        jList1.setModel(listModel); 
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextArea1.setText("");
    }
    public void refreshItemList(String filterString) {

        String query;
        switch(userValue){
            case 0:{ //Admin=0
             query = "SELECT BLNumber FROM "+PropertiesClass.props.DB_NAME+".Transports WHERE `BLNumber` LIKE '"+filterString+"%' ;";
            }break;
            case 1:{ //Buyer=1
             query = "SELECT BLNumber FROM "+PropertiesClass.props.DB_NAME+".Transports WHERE `BLNumber` LIKE '"+filterString+"%' ;";
            }break;
            case 2:{ //Vendor=2
             query = "SELECT BLNumber FROM "+PropertiesClass.props.DB_NAME+".Transports a, "+PropertiesClass.props.DB_NAME+".Status b WHERE a.Status_ID=b.ID AND a.UpdatedBy='"+userMail+"' AND (b.DataName='Opened' OR b.DataName='Completed' OR b.DataName='AC' OR b.DataName='Reopened') AND a.`BLNumber` LIKE '"+filterString+"%' ;";
            }break;
            case 3:{ //PU=3
             query = "SELECT BLNumber FROM "+PropertiesClass.props.DB_NAME+".Transports a, "+PropertiesClass.props.DB_NAME+".Status b WHERE a.Status_ID=b.ID AND (b.DataName='Opened' OR b.DataName='AC' OR b.DataName='Reopened') AND a.`BLNumber` LIKE '"+filterString+"%' ;";
            }break;
            case 4:{ //Impex=4
             query = "SELECT BLNumber FROM "+PropertiesClass.props.DB_NAME+".Transports a, "+PropertiesClass.props.DB_NAME+".Status b WHERE a.Status_ID=b.ID AND (b.DataName='Opened' OR b.DataName='Completed' OR b.DataName='Rejected' OR b.DataName='Correct' OR b.DataName='Archived' OR b.DataName='AC' OR b.DataName='Reopened') AND a.`BLNumber` LIKE '"+filterString+"%' ;";
            }break;
            case 5:{ //Customs Agency=5
             //ver.1.01 Customs Agency must see all types of events -- 28.08.2014
             //query = "SELECT BLNumber FROM "+PropertiesClass.props.DB_NAME+".Transports a, "+PropertiesClass.props.DB_NAME+".Status b WHERE a.Status_ID=b.ID AND (b.DataName='Completed' OR b.DataName='Correct' OR b.DataName='AC' OR b.DataName='Reopened') AND a.`BLNumber` LIKE '"+filterString+"%' ;";
             query = "SELECT BLNumber FROM "+PropertiesClass.props.DB_NAME+".Transports a, "+PropertiesClass.props.DB_NAME+".Status b WHERE a.Status_ID=b.ID AND (b.DataName!='Opened') AND a.`BLNumber` LIKE '"+filterString+"%' ;"; //AC don't want to see 'opened' status ver.1.01  -- 01.11.2014
            }break;
            case 6:{ //Transport=6
             query = "SELECT BLNumber FROM "+PropertiesClass.props.DB_NAME+".Transports WHERE `BLNumber` LIKE '"+filterString+"%' ;";
            }break;
            //ver.1.02 Added new user group (Courier) -- 30.11.2014    
            case 7:{ //Courier=7
             query = "SELECT BLNumber FROM "+PropertiesClass.props.DB_NAME+".Transports a, "+PropertiesClass.props.DB_NAME+".Carrier b WHERE a.Carrier_ID = b.ID AND b.DataName ='"+userCarrier+"' AND a.`BLNumber` LIKE '"+filterString+"%';"; 
            }break;
            default:{
             query = "SELECT BLNumber FROM "+PropertiesClass.props.DB_NAME+".Transports WHERE `BLNumber` LIKE '"+filterString+"%' ;";    
            }break;
        }
        DefaultListModel listModel = new DefaultListModel();       
        eventNames = sqlConnector.getQueryFirstColumn(query);

        for (int i = 0; i < eventNames.length; i++) {
            listModel.addElement(eventNames[i]);
        }
        jList1.setModel(listModel); 
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextArea1.setText("");
    }
    private void loadItemDetails(int selectedIndex){
               
        String query = "SELECT t.BLNumber, t.PONumber,t.UpdatedBy, t.UpdatedDate, u.Login, v.DataName, c.DataName, s.DataName FROM "+PropertiesClass.props.DB_NAME+".Transports t,"+PropertiesClass.props.DB_NAME+".User u,"+PropertiesClass.props.DB_NAME+".Vendor v,"+PropertiesClass.props.DB_NAME+".Carrier c, "+PropertiesClass.props.DB_NAME+".Status s WHERE t.Buyer_ID = u.ID AND t.Vendor_ID=v.ID AND t.Carrier_ID=c.ID AND t.Status_ID=s.ID AND t.BLNumber = '"+eventNames[selectedIndex]+"';";
        String[] vendorDetails = sqlConnector.getQueryFirstRow(query,8);
        jTextField1.setText(vendorDetails[0]);
        jTextField2.setText(vendorDetails[1]);
        jTextField4.setText(vendorDetails[2]);
        jTextField5.setText(vendorDetails[3]);
        jTextField3.setText(vendorDetails[4]);
        jTextField8.setText(vendorDetails[5]);
        jTextField7.setText(vendorDetails[6]);
        jTextField6.setText(vendorDetails[7]);
        query ="SELECT a.Comment FROM "+PropertiesClass.props.DB_NAME+".Comments a, "+PropertiesClass.props.DB_NAME+".Transports b WHERE a.Transports_ID = b.ID AND b.BLNumber='"+eventNames[selectedIndex]+"' ORDER BY a.UpdatedDate ASC;";
        String [] comments = sqlConnector.getQueryFirstColumn(query);
        String allComments = "";
        for(int i=0;i<comments.length;i++)
        {       
            allComments+=comments[i]+"\n";
        }
        jTextArea1.setText(allComments);
        query = "SELECT a.ID FROM  "+PropertiesClass.props.DB_NAME+".LinkedDoc a, "+PropertiesClass.props.DB_NAME+".Transports b WHERE a.Transports_ID = b.ID AND b.BLNumber='"+eventNames[selectedIndex]+"';";
        String[] files = sqlConnector.getQueryFirstColumn(query);
        int length = files.length;
        jTextField9.setText(Integer.toString(length));
        try{
        if(length!=0) setImageIcon("Images/spinacz.png");
        else setImageIcon("Images/default.png");
        }catch(Exception e){System.out.println("Nie znaleziono pliku z grafiką");
        System.out.println(getClass().getClassLoader().getResource("/Images/spinacz.png"));}
           
    }
    private void setImageIcon(String path) throws IOException{
        BufferedImage myPicture = ImageIO.read(getClass().getClassLoader().getResource(path));
        labelImage.setIcon(new ImageIcon( myPicture ));
        
        
    }
   // private BufferedImage resizeImage(BufferedImage originalImage, int type){
	//BufferedImage resizedImage = new BufferedImage(IMG_WIDTH, IMG_HEIGHT, type);
	//Graphics2D g = resizedImage.createGraphics();
	//g.drawImage(originalImage, 0, 0, IMG_WIDTH, IMG_HEIGHT, null);
	//g.dispose();
 
	//return resizedImage;
   // }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RefreshButton;
    private javax.swing.JButton carrierButton;
    private javax.swing.JButton changePassButton;
    private javax.swing.JButton eventCommentsButton;
    private javax.swing.JButton eventDocumentsButton;
    private javax.swing.JButton eventStatusButton;
    private javax.swing.JTextField filterTextField;
    private javax.swing.JButton groupsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel labelImage;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel logoLabel2;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton logsButton;
    private javax.swing.JButton newEventButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton statusesButton;
    private javax.swing.JButton usersButton;
    private javax.swing.JButton vendorButton;
    // End of variables declaration//GEN-END:variables
}
