/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Classes.FileManager;
import Classes.MailSender;
import Classes.PropertiesClass;
import Classes.SQLConnection;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author Sowa
 */
public class UploadPanel extends javax.swing.JPanel {

    /**
     * Creates new form UploadPanel
     */
    public static UploadPanel uploadPanel;
    SQLConnection sqlConnector;
    File [] files;
    String filesNames;
    int selectedEventID;
    String selectedEvent;
    
    public UploadPanel(int selectedEventID, String selectedEvent) {
        initComponents();
        uploadPanel = this;
        this.selectedEventID=selectedEventID;
        this.selectedEvent=selectedEvent;
        sqlConnector=SQLConnection.sqlConnector;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uploadButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        browseButton = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));

        uploadButton.setText("Upload Files");
        uploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("BACK");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);

        jLabel1.setText("File Path:");

        jLabel6.setText("File Name:");

        jLabel7.setText("File Type:");

        browseButton.setText("Browse");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("File Active");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setText("File Description:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(uploadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2)
                                    .addComponent(jTextField3)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox1)
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addComponent(browseButton)
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(browseButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(uploadButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1)
                .addContainerGap(277, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void uploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadButtonActionPerformed
        if(!jTextField1.getText().isEmpty()){            
            String query = "SELECT ID FROM "+PropertiesClass.props.DB_NAME+".Transports WHERE BLNumber='"+selectedEvent+"'";
            int transportID = Integer.parseInt(sqlConnector.getQueryFirstElement(query));
            if(files.length==1){
             query = "SELECT * FROM "+PropertiesClass.props.DB_NAME+".LinkedDoc WHERE FileName='"+jTextField2.getText()+"' AND Transports_ID = '"+transportID+"'";
            if (!sqlConnector.checkQueryAppearence(query)){   
            FileManager.fileManager.fileWrite(files[0],jTextField2.getText(),jTextArea1.getText(),MainPanel.mainPanel.userLogin,jCheckBox1.isSelected(),transportID); // inserting file into database
            sqlConnector.addLogToTable("File Uploaded", MainPanel.userLogin, jTextField2.getText(), selectedEventID);
            JOptionPane.showMessageDialog(this, "File uploaded.");
            if(MainPanel.mainPanel.userGroup.contentEquals("Vendor")) sendMailsToBuyer(jTextField2.getText());
            DocumentsPanel.documentsPanel.refreshItemList();
            }else JOptionPane.showMessageDialog(this, "File with that name already exist! change name of the file.");   
            }else //ver.1.01   uploading multiple files 19-10-2014
            {
                for(File file : files)
             {
                query = "SELECT * FROM "+PropertiesClass.props.DB_NAME+".LinkedDoc WHERE FileName='"+file.getName()+"' AND Transports_ID = '"+transportID+"'";
                if (!sqlConnector.checkQueryAppearence(query)){   
                FileManager.fileManager.fileWrite(file,file.getName(),jTextArea1.getText(), MainPanel.mainPanel.userLogin, true,transportID); // inserting file into database
                sqlConnector.addLogToTable("File Uploaded", MainPanel.userLogin, file.getName(), selectedEventID);               
                }else JOptionPane.showMessageDialog(this, "File: \""+ file.getName()+"\" already exist! This file will not be uploaded."); 
             }
                JOptionPane.showMessageDialog(this, "Files uploaded.");
                if(MainPanel.mainPanel.userGroup.contentEquals("Vendor")) sendMailsToBuyer(filesNames);
                DocumentsPanel.documentsPanel.refreshItemList();   
                  
            }
            
        }
        else JOptionPane.showMessageDialog(this, "Chose file first!");

        
    }//GEN-LAST:event_uploadButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        uploadPanel.setVisible(false);
        DocumentsPanel.documentsPanel.setVisible(true);
    }//GEN-LAST:event_cancelButtonActionPerformed
    private void sendMails(String fileName){
        
        
        String query = "SELECT a.`E-mail` FROM "+PropertiesClass.props.DB_NAME+".User a, mydb.Group b WHERE a.Group_ID=b.ID AND b.DataName='PU';";
        String [] PUMails = sqlConnector.getQueryFirstColumn(query);
        MailSender mail= new MailSender();
         try{            
            mail.send(PUMails,"New Document Loaded","New document has been loaded. BLNumber: "+selectedEvent+". Document Name: "+fileName+".");
         }catch(Exception e){System.out.println("Błąd w mailu: "+e);}
    
    }
    private void sendMailsToBuyer(String fileName){
               
        String query = "SELECT a.`E-mail` FROM "+PropertiesClass.props.DB_NAME+".User a, "+PropertiesClass.props.DB_NAME+".Transports b  WHERE b.ID="+selectedEventID+" AND b.Buyer_ID = a.ID ;";
        String [] BuyerMails = sqlConnector.getQueryFirstColumn(query);
        MailSender mail= new MailSender();
         try{            
            mail.send(BuyerMails,"New documents attached","New documents has been attached to Event:\nBLNumber: "+selectedEvent+".\nDocument Name: "+fileName+".");
         }catch(Exception e){System.out.println("Błąd w mailu: "+e);}
    
    }
    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setMultiSelectionEnabled(true);
        chooser.setFileHidingEnabled(true);
        File oldFile = new File(jTextField1.getText());
        if (oldFile.getAbsolutePath().isEmpty())chooser.setCurrentDirectory(null);
        else chooser.setCurrentDirectory(oldFile);        
        int returnVal = chooser.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            files = chooser.getSelectedFiles(); // path to file
            if(files.length==1){
            String fileName = files[0].getName();
            int dotIndex = fileName.lastIndexOf(".");
            String fileType = fileName.substring(dotIndex);
            jTextField1.setText(files[0].getPath());
            jTextField2.setText(fileName);
            jTextField3.setText(fileType);
            } else //ver.1.01   uploading multiple files 19-10-2014
            {
                filesNames="";
                for(File file : files)
             {
                 filesNames+=file.getName()+";";
             }
             jTextField1.setText(filesNames);
             jTextField2.setText("Multiple choice");
             jTextField3.setText("Multiple choice");   
            }
        }
    }//GEN-LAST:event_browseButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton uploadButton;
    // End of variables declaration//GEN-END:variables
}
